package uepb.sysjavou.ui;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import uepb.sysjavou.Banco;
import uepb.sysjavou.Cliente;
import uepb.sysjavou.Conta;
import uepb.sysjavou.Contato;
import uepb.sysjavou.Endereco;

public class frmCadastro extends javax.swing.JDialog {
    
    private Cliente cliente;
    private int action; //0 = Excluir; 1 = Atualizar; 2 = Novo
    private UI ui = new UI("SYSJAVOU 1.0 - CADASTRO");
    private ArrayList<Conta> contas;
    private Banco banco;
    
    public frmCadastro(Banco banco) {
        initComponents();
        this.banco = banco;
    }
    public void showForm(Cliente cliente){
        this.cliente = cliente;
        this.action = -1;
        
        Object[][] obj;
        int i = 0;
        
        if(cliente != null){
            this.contas = cliente.getContas();
            obj = new Object[cliente.getContas().size()][2];
            for(Conta c : cliente.getContas()){
                obj[i][0] = c.getAgencia();
                obj[i][1] = c.getNumeroConta();
                i++;
            }
            this.tblContas.setModel(new DefaultTableModel(obj, new String[] {"Agencia", "Conta"}));
            i = 0;
            
            this.txtbCPF.setText(cliente.getCpf());
            this.txtbCelular.setText(cliente.getContato().getCelularSemFormatacao());
            this.txtbEmail.setText(cliente.getContato().getEmail());
            this.txtbIdade.setText(String.valueOf(cliente.getIdade()));
            this.txtbLog.setText(cliente.getEndereco().getLogradouro());
            this.txtbLogBairro.setText(cliente.getEndereco().getBairro());
            this.txtbLogCidade.setText(cliente.getEndereco().getCidade());
            this.txtbLogEstado.setText(cliente.getEndereco().getUf());
            this.txtbLogNumero.setText(String.valueOf(cliente.getEndereco().getNumero()));
            this.txtbLogPais.setText(cliente.getEndereco().getPais());
            this.txtbLogTipo.setText(cliente.getEndereco().getTipoLogradouro());
            this.txtbNome.setText(cliente.getNome());
            this.txtbRedeSocial.setText(cliente.getContato().getRedeSocial());
            this.txtbTelefone.setText(cliente.getContato().getTelefoneSemFormatacao());
            
        }else{
            this.contas = new ArrayList();
            this.tblContas.setModel(new DefaultTableModel(null, new String[] {"Agencia", "Conta"}));
        }
        this.setLocationRelativeTo(null);
        this.setModal(true);
        this.setVisible(true);
    }
    public Cliente getCliente(){
        return this.cliente;
    }
    public int getAction(){
        return this.action;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtbNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtbCPF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtbIdade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtbEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtbRedeSocial = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtbTelefone = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtbCelular = new javax.swing.JTextField();
        selectBoxSexoM = new javax.swing.JCheckBox();
        selectBoxSexoF = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        txtbLogTipo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtbLog = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtbLogNumero = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtbLogBairro = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtbLogCidade = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtbLogEstado = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtbLogPais = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblContas = new javax.swing.JTable();
        btAddConta = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btRemoveConta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("CADASTRAR/ALTERAR CLIENTE");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setOpaque(true);
        jLabel2.setRequestFocusEnabled(false);

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nome do Cliente:");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("CPF");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Idade");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Sexo");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Email:");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Rede Social");

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Telefone:");

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Celular:");

        selectBoxSexoM.setForeground(new java.awt.Color(0, 0, 0));
        selectBoxSexoM.setText("Masculino");
        selectBoxSexoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBoxSexoMActionPerformed(evt);
            }
        });

        selectBoxSexoF.setForeground(new java.awt.Color(0, 0, 0));
        selectBoxSexoF.setText("Feminino");
        selectBoxSexoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBoxSexoFActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Tipo do Logradouro:");

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Logradouro:");

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Nº:");

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Bairro:");

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Cidade:");

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Estado(Sigla):");

        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("País(Sigla):");

        tblContas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblContas);

        btAddConta.setText("Adicionar Conta");
        btAddConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddContaActionPerformed(evt);
            }
        });

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir Cliente");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btRemoveConta.setText("Excluir Conta");
        btRemoveConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoveContaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btRemoveConta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAddConta))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btExcluir))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtbIdade))
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(selectBoxSexoM)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(selectBoxSexoF)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtbEmail))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtbNome, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtbCPF))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(140, 140, 140)
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtbLogCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtbLogEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtbLogBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(250, 250, 250)
                                        .addComponent(jLabel16)
                                        .addGap(92, 92, 92)))
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtbLogPais, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtbTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtbCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtbRedeSocial))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtbLogTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtbLog)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtbLogNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtbCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(txtbEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(selectBoxSexoM)
                    .addComponent(selectBoxSexoF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtbRedeSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtbCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbLogTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtbLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtbLogNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbLogBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtbLogCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtbLogEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txtbLogPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAddConta)
                    .addComponent(btRemoveConta))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar)
                    .addComponent(btExcluir))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectBoxSexoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBoxSexoFActionPerformed
        if(this.selectBoxSexoM.isSelected()){
            this.selectBoxSexoM.setSelected(false);
        }
    }//GEN-LAST:event_selectBoxSexoFActionPerformed

    private void selectBoxSexoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBoxSexoMActionPerformed
        if(this.selectBoxSexoF.isSelected()){
            this.selectBoxSexoF.setSelected(false);
        }
    }//GEN-LAST:event_selectBoxSexoMActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        this.action = 0;
        this.setVisible(false);
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        if(!this.txtbCPF.getText().equals("") && !this.txtbCelular.getText().equals("") 
                && !this.txtbEmail.getText().equals("") && !this.txtbIdade.getText().equals("")
                && !this.txtbLog.getText().equals("") && !this.txtbLogBairro.getText().equals("")
                && !this.txtbLogCidade.getText().equals("") && !this.txtbLogEstado.getText().equals("")
                && !this.txtbLogNumero.getText().equals("") && !this.txtbLogPais.getText().equals("")
                && !this.txtbLogTipo.getText().equals("") && !this.txtbNome.getText().equals("")
                && !this.txtbRedeSocial.getText().equals("") && !this.txtbTelefone.getText().equals("")){
                //Salva no objeto
                
                if(this.txtbCPF.getText().matches("[0-9]+") && this.txtbIdade.getText().matches("[0-9]+") &&
                        this.txtbCelular.getText().matches("[0-9]+") && this.txtbLogNumero.getText().matches("[0-9]+") && 
                                this.txtbTelefone.getText().matches("[0-9]+")){
                    
                    if(cliente == null){
                        Cliente c = banco.getCliente(this.txtbNome.getText());
                        
                        if(c == null){
                            c = banco.getClientebyCPF(this.txtbCPF.getText());
                            
                            if(c == null){
                                cliente = new Cliente();
                                cliente.setCpf(String.valueOf(this.txtbCPF.getText()));
                                cliente.setNome(String.valueOf(this.txtbNome.getText()));
                                cliente.setIdade(Integer.parseInt(String.valueOf(this.txtbIdade.getText())));
                                cliente.setContato(new Contato(String.valueOf(this.txtbEmail.getText()), String.valueOf(this.txtbTelefone.getText()), 
                                                                String.valueOf(this.txtbCelular.getText()), String.valueOf(this.txtbRedeSocial.getText())));
                                cliente.setEndereco(new Endereco(String.valueOf(this.txtbLogPais.getText()), String.valueOf(this.txtbLogEstado.getText()),
                                                                    String.valueOf(this.txtbLogCidade.getText()), String.valueOf(this.txtbLogBairro.getText()),
                                                                    String.valueOf(this.txtbLog.getText()), Integer.parseInt(String.valueOf(this.txtbLogNumero.getText())),
                                                                    String.valueOf(this.txtbLogTipo.getText())));
                                if(this.selectBoxSexoF.isSelected()){
                                    cliente.setSexo('F');
                                }
                                if(this.selectBoxSexoM.isSelected()){
                                    cliente.setSexo('M');
                                }
                                cliente.setContas(contas);
                                this.action = 2;
                                this.setVisible(false);
                            }else{
                                ui.showMsg("Esse CPF ja esta cadastrado!");
                            }
                        }else{
                            ui.showMsg("Esse nome ja esta cadastrado!");
                        }
                    }else{
                        Cliente c = banco.getCliente(this.txtbNome.getText());
                        String auxStr;
                        try{
                            auxStr = c.getNome();
                        }catch(Exception e){
                            auxStr = "";
                        }
                        
                        if(auxStr.equals("") || auxStr.equals(cliente.getNome())){
                            c = banco.getClientebyCPF(this.txtbCPF.getText());
                            try{
                                auxStr = c.getCpf();
                            }catch(Exception e){
                                auxStr = "";
                            }
                            
                            if(auxStr.equals("") || auxStr.equals(cliente.getCpf())){
                                cliente.setCpf(String.valueOf(this.txtbCPF.getText()));
                                cliente.setNome(String.valueOf(this.txtbNome.getText()));
                                cliente.setIdade(Integer.parseInt(String.valueOf(this.txtbIdade.getText())));
                                cliente.setContato(new Contato(String.valueOf(this.txtbEmail.getText()), String.valueOf(this.txtbTelefone.getText()), 
                                                                String.valueOf(this.txtbCelular.getText()), String.valueOf(this.txtbRedeSocial.getText())));
                                cliente.setEndereco(new Endereco(String.valueOf(this.txtbLogPais.getText()), String.valueOf(this.txtbLogEstado.getText()),
                                                                    String.valueOf(this.txtbLogCidade.getText()), String.valueOf(this.txtbLogBairro.getText()),
                                                                    String.valueOf(this.txtbLog.getText()), Integer.parseInt(String.valueOf(this.txtbLogNumero.getText())),
                                                                    String.valueOf(this.txtbLogTipo.getText())));
                                if(this.selectBoxSexoF.isSelected()){
                                    cliente.setSexo('F');
                                }
                                if(this.selectBoxSexoM.isSelected()){
                                    cliente.setSexo('M');
                                }
                                cliente.setContas(contas);
                                this.action = 1;
                                this.setVisible(false);
                            }else{
                                    ui.showMsg("Esse CPF ja esta cadastrado em outra pessoa!");
                            }
                        }else{
                            ui.showMsg("Esse nome ja esta cadastrado em outra pessoa!");
                        }
                    }
                }else{
                    ui.showMsg("Por favor digite apenas numeros nos campos de CPF, IDADE, CELULAR, TELEFONE e NUMERO DA RESIDENCIA!!");
                }
                
        }else{
            ui.showMsg("Por favor preencha todos os campos!");
        }       
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btAddContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddContaActionPerformed
        DefaultTableModel model = (DefaultTableModel) this.tblContas.getModel();
        Cliente c;
        
        String agencia = ui.askTextOnlyNumbers("Por favor digite a Agência!", "Digite apenas Numeros!");
        String conta = ui.askTextOnlyNumbers("Por favor digite a Conta!", "Digite apenas Numeros!");
        c = banco.getClientebyConta(Integer.parseInt(agencia), Integer.parseInt(conta));
        
        if(c == null){
            boolean teste = false;
            
            for(int i = 0; i < model.getRowCount(); i++){
                if(String.valueOf(model.getValueAt(i, 0)).equals(String.valueOf(agencia)) &&
                String.valueOf(model.getValueAt(i, 1)).equals(String.valueOf(conta))){
                    teste = true;
                }
            }
            if(!teste){
               contas.add(new Conta(Integer.parseInt(agencia), Integer.parseInt(conta)));
                model.addRow(new Object[] {agencia, conta});
                this.tblContas.setModel(model); 
            }else{
                ui.showMsg("Essa conta ja esta cadastrada!");
            }
            
        }else{
            ui.showMsg("Essa conta ja esta cadastrada!");
        }
    }//GEN-LAST:event_btAddContaActionPerformed

    private void btRemoveContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoveContaActionPerformed
        DefaultTableModel model = (DefaultTableModel) this.tblContas.getModel();
        
        String agencia = ui.askTextOnlyNumbers("Por favor digite a Agência!", "Digite apenas Numeros!");
        String conta = ui.askTextOnlyNumbers("Por favor digite a Conta!", "Digite apenas Numeros!");
        int i = 0;
        
        for(i = 0; i < this.contas.size(); i++){
            if(this.contas.get(i).getAgencia() == Integer.parseInt(agencia) &&
                    this.contas.get(i).getNumeroConta() == Integer.parseInt(conta)){
                this.contas.remove(i);
                i++;
            }
        }
        for(i = 0; i < this.tblContas.getRowCount(); i ++){
            if(String.valueOf(model.getValueAt(i, 0)).equals(String.valueOf(agencia)) && 
                    String.valueOf(model.getValueAt(i, 1)).equals(String.valueOf(conta))){
                model.removeRow(i);
            }
        }
        
        this.tblContas.setModel(model);
    }//GEN-LAST:event_btRemoveContaActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddConta;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btRemoveConta;
    private javax.swing.JButton btSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox selectBoxSexoF;
    private javax.swing.JCheckBox selectBoxSexoM;
    private javax.swing.JTable tblContas;
    private javax.swing.JTextField txtbCPF;
    private javax.swing.JTextField txtbCelular;
    private javax.swing.JTextField txtbEmail;
    private javax.swing.JTextField txtbIdade;
    private javax.swing.JTextField txtbLog;
    private javax.swing.JTextField txtbLogBairro;
    private javax.swing.JTextField txtbLogCidade;
    private javax.swing.JTextField txtbLogEstado;
    private javax.swing.JTextField txtbLogNumero;
    private javax.swing.JTextField txtbLogPais;
    private javax.swing.JTextField txtbLogTipo;
    private javax.swing.JTextField txtbNome;
    private javax.swing.JTextField txtbRedeSocial;
    private javax.swing.JTextField txtbTelefone;
    // End of variables declaration//GEN-END:variables
}
