package uepb.sysjavou.ui;

import javax.swing.table.DefaultTableModel;

public class frmListarTransacoes extends javax.swing.JDialog {

    public frmListarTransacoes(Object[][] src, String[] headers, int agencia, int conta, String nome, String CPF) {
        initComponents();
        this.tblTransacoes.setModel(new DefaultTableModel(src, headers));
        this.lblAgencia.setText("Agencia: " + agencia);
        this.lblConta.setText("Conta: " + conta);
        this.lblNomePessoa.setText("Nome: " + nome);
        this.lblCPF.setText("CPF: " + CPF);
        this.setModal(true);
        this.setTitle("TRANSAÇÕES");
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTransacoes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblAgencia = new javax.swing.JLabel();
        lblConta = new javax.swing.JLabel();
        lblLineModel = new javax.swing.JLabel();
        lblNomePessoa = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setSize(new java.awt.Dimension(742, 366));

        tblTransacoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTransacoes);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("TRANSAÇÕES BANCARIAS");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Filtragem Utilizada:");

        lblAgencia.setBackground(new java.awt.Color(0, 0, 0));
        lblAgencia.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblAgencia.setForeground(new java.awt.Color(0, 0, 0));
        lblAgencia.setText("Agencia: *");

        lblConta.setBackground(new java.awt.Color(0, 0, 0));
        lblConta.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblConta.setForeground(new java.awt.Color(0, 0, 0));
        lblConta.setText("Conta: *");

        lblLineModel.setBackground(new java.awt.Color(0, 0, 0));
        lblLineModel.setForeground(new java.awt.Color(0, 0, 0));
        lblLineModel.setOpaque(true);

        lblNomePessoa.setBackground(new java.awt.Color(0, 0, 0));
        lblNomePessoa.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblNomePessoa.setForeground(new java.awt.Color(0, 0, 0));
        lblNomePessoa.setText("Nome da Pessoa: *");

        lblCPF.setBackground(new java.awt.Color(0, 0, 0));
        lblCPF.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblCPF.setForeground(new java.awt.Color(0, 0, 0));
        lblCPF.setText("CPF da Pessoa: *");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLineModel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCPF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNomePessoa, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                            .addComponent(lblConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAgencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLineModel, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAgencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblConta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNomePessoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCPF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAgencia;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblConta;
    private javax.swing.JLabel lblLineModel;
    private javax.swing.JLabel lblNomePessoa;
    private javax.swing.JTable tblTransacoes;
    // End of variables declaration//GEN-END:variables
}
